IMAGE_NAME = "bento/debian-13"
 
Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
 
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
    end
 
    config.vm.define "debian" do |debian|
        debian.vm.box = IMAGE_NAME
 
        # SSH port forwarding
        debian.vm.network "forwarded_port",
            guest: 22,
            host: 2206,
            host_ip: "127.0.0.1"
 
        # Interní síť (stejná jako Zabbix Appliance)
        debian.vm.network "private_network",
            ip: "192.168.1.10",
            virtualbox__intnet: "intnet"
 
        debian.vm.hostname = "debian"
    end
 
    config.vm.provision "shell", path: "zbx_config.sh"
end